version: "3.9"

services:
  jupyter:
    build:
      context: . 
      dockerfile: "./ml-jupyter/Dockerfile"
    restart: always 
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=""
      --notebook-dir="/workspace/ml-jupyter/"
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "./:/workspace"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
